version: '3.7'

services:

  dev:
    container_name: snail-board-frontend
    build:
      context: ../SnailBoardFrontend
      dockerfile: Dockerfile.dev
    volumes:
      - '../SnailBoardFrontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
