version: '3.7'

services:
  front:
    container_name: snail-board-frontend
    build:
      context: ../SnailBoardFrontend
      dockerfile: Dockerfile.dev
    volumes:
      - '../SnailBoardFrontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: snailboard
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    hostname: mysql
    container_name: db

  backend:
    container_name: snail-board-backend
    ports:
      - 8081:8081
    build:
      context: ../SnailBoardBackend
      dockerfile: Dockerfile.dev
    environment:
      - DB_URL=jdbc:mysql://db:3306/snailboard
    depends_on:
      - db